// <auto-generated />
using LogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogAPI.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20220805122618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27");

            modelBuilder.Entity("LogAPI.Entities.LogEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(20);

                    b.Property<string>("ComponentName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(20);

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("TraceID")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.ToTable("LogEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
